theme = "showfolio"
languageCode = "en-us"
baseurl = "https://daniloderosa.netlify.app"
title = "Danilo De Rosa"


[params]
  name = "Danilo De Rosa"
  description = "Danilo De Rosa's work"
  author = "Danilo De Rosa"
  authorEmail = "danilo.derosa.dd@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright Â© 2021 - Danilo De Rosa Â· All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey ðŸ‘‹ I'm Danilo De Rosa"
  tagline = "Data editor"
  description = "I research, clean, analyze and visualize data."
  contact = "https://twitter.com/"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Visual Design", "Product Development"]

[[params.homepage.resume.work]]
  name = "Google"
  role = "Product Engineer"
  duration = "Nov 2019 - Apr 2021"

[[params.homepage.resume.work]]
  name = "Amazon"
  role = "Sr. UX Designer"
  duration = "Jan 2016 - Oct 2019"

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
